#!/usr/bin/env sh
set -eu

SCRIPT_NAME="scripts/setup.sh"
HOOK_MARKER="Generated by scripts/setup.sh for merge-tsconfigs"
CURRENT_TMP_HOOK=""

cleanup() {
  if [ -n "$CURRENT_TMP_HOOK" ] && [ -e "$CURRENT_TMP_HOOK" ]; then
    rm -f "$CURRENT_TMP_HOOK"
  fi
}

trap cleanup EXIT
trap 'cleanup; exit 1' HUP INT TERM

log() {
  printf '%s\n' "$*"
}

fail() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    fail "$1 is required. Install it, then rerun $SCRIPT_NAME."
  fi
}

clear_legacy_husky_hooks_path() {
  hooks_path="$(git config --get core.hooksPath 2>/dev/null || true)"

  case "$hooks_path" in
    .husky | .husky/ | .husky/_ | .husky/_/ | */.husky | */.husky/ | */.husky/_ | */.husky/_/)
      git config --unset core.hooksPath || true
      log "Cleared legacy core.hooksPath=$hooks_path"
      ;;
  esac
}

write_pre_commit_hook() {
  target_path="$1"
  cat >"$target_path" <<'HOOK'
#!/usr/bin/env sh
set -eu

# Generated by scripts/setup.sh for merge-tsconfigs

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"

pnpm run pre-commit
HOOK
}

write_commit_msg_hook() {
  target_path="$1"
  cat >"$target_path" <<'HOOK'
#!/usr/bin/env sh
set -eu

# Generated by scripts/setup.sh for merge-tsconfigs

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"

pnpm run commit-msg -- "$1"
HOOK
}

write_post_merge_hook() {
  target_path="$1"
  cat >"$target_path" <<'HOOK'
#!/usr/bin/env sh
set -eu

# Generated by scripts/setup.sh for merge-tsconfigs

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"

changed="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD 2>/dev/null || true)"

if printf '%s\n' "$changed" | grep -qE '(^|/)(package\.json|pnpm-lock\.yaml)$'; then
  pnpm install --frozen-lockfile
fi
HOOK
}

install_hook() {
  hook_name="$1"
  hook_path="$(git rev-parse --git-path "hooks/$hook_name")"
  hook_dir="$(dirname "$hook_path")"
  tmp_path="$hook_path.tmp.$$"

  mkdir -p "$hook_dir"
  CURRENT_TMP_HOOK="$tmp_path"

  case "$hook_name" in
    pre-commit)
      write_pre_commit_hook "$tmp_path"
      ;;
    commit-msg)
      write_commit_msg_hook "$tmp_path"
      ;;
    post-merge)
      write_post_merge_hook "$tmp_path"
      ;;
    *)
      fail "unsupported hook: $hook_name"
      ;;
  esac

  chmod +x "$tmp_path"

  if [ -e "$hook_path" ] && grep -q "$HOOK_MARKER" "$hook_path" 2>/dev/null; then
    if cmp -s "$tmp_path" "$hook_path"; then
      chmod +x "$hook_path"
      rm -f "$tmp_path"
      CURRENT_TMP_HOOK=""
      log "$hook_name hook already installed"
      return 0
    fi

    mv "$tmp_path" "$hook_path"
    CURRENT_TMP_HOOK=""
    log "Updated $hook_name hook"
    return 0
  fi

  if [ -e "$hook_path" ] && ! grep -q "$HOOK_MARKER" "$hook_path" 2>/dev/null; then
    backup_path="$hook_path.backup.$(date +%Y%m%d%H%M%S)"
    if [ -e "$backup_path" ]; then
      backup_path="$backup_path.$$"
    fi
    mv "$hook_path" "$backup_path"
    log "Backed up existing $hook_name hook to $backup_path"
  fi

  mv "$tmp_path" "$hook_path"
  CURRENT_TMP_HOOK=""
  log "Installed $hook_name hook"
}

main() {
  if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
    log "Usage: $SCRIPT_NAME"
    log "Installs merge-tsconfigs Git hooks."
    return 0
  fi

  if [ "$#" -ne 0 ]; then
    fail "unexpected arguments. Run '$SCRIPT_NAME --help' for usage."
  fi

  if [ "${CI:-}" = "true" ] || [ "${CI:-}" = "1" ]; then
    log "CI detected; skipping Git hook setup"
    return 0
  fi

  if ! command -v git >/dev/null 2>&1; then
    log "git not found; skipping Git hook setup"
    return 0
  fi

  require_command pnpm

  repo_root="$(git rev-parse --show-toplevel 2>/dev/null)" || {
    log "No Git repository found; skipping Git hook setup"
    return 0
  }
  cd "$repo_root"

  clear_legacy_husky_hooks_path

  install_hook pre-commit
  install_hook commit-msg
  install_hook post-merge

  log "merge-tsconfigs development setup complete"
}

main "$@"
