/**
 * @description: this is used to configure dynamic tsconfig options
 */
export const compilerOptions = {
  target: "string",
  module: "string",
  lib: "array",
  allowJs: "boolean",
  checkJs: "boolean",
  jsx: "string",
  declaration: "boolean",
  sourceMap: "boolean",
  outFile: "string",
  outDir: "string",
  rootDir: "string",
  removeComments: "boolean",
  noEmit: "boolean",
  importHelpers: "boolean",
  downlevelIteration: "boolean",
  isolatedModules: "boolean",
  strict: "boolean",
  noImplicitAny: "boolean",
  strictNullChecks: "boolean",
  noImplicitThis: "boolean",
  alwaysStrict: "boolean",
  noUnusedLocals: "boolean",
  noUnusedParameters: "boolean",
  noImplicitReturns: "boolean",
  noFallthroughCasesInSwitch: "boolean",
  moduleResolution: "string",
  baseUrl: "string",
  paths: "object",
  rootDirs: "array",
  typeRoots: "array",
  types: "array",
  allowSyntheticDefaultImports: "boolean",
  sourceRoot: "string",
  mapRoot: "string",
  inlineSourceMap: "boolean",
  inlineSources: "boolean",
  experimentalDecorators: "boolean",
  emitDecoratorMetadata: "boolean"
}
